package com.smartherd.msgshareapp.models

data class Hobby(var title: String)

object Supplier {

    val hobbies = listOf(
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Movies"),
        Hobby("Dinning"),
        Hobby("Theaters"),
        Hobby("Walking / Hiking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Movies"),
        Hobby("Dinning"),
        Hobby("Theaters"),
        Hobby("Walking / Hiking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Movies"),
        Hobby("Dinning"),
        Hobby("Theaters"),
        Hobby("Walking / Hiking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Movies"),
        Hobby("Dinning"),
        Hobby("Theaters"),
        Hobby("Walking / Hiking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Movies"),
        Hobby("Dinning"),
        Hobby("Theaters"),
        Hobby("Walking / Hiking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Movies"),
        Hobby("Dinning"),
        Hobby("Theaters"),
        Hobby("Walking / Hiking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Movies"),
        Hobby("Dinning"),
        Hobby("Theaters"),
        Hobby("Walking / Hiking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Movies"),
        Hobby("Dinning"),
        Hobby("Theaters"),
        Hobby("Walking / Hiking")
    )
}